namespace dvbapiNet.Dvb.Descriptors
{
    public enum DescriptorTag : byte
    {
        // iso iec 13818-1 (05/2006)
        VideoStream = 2,

        AudioStream = 3,
        Hierarchy = 4,
        Registration = 5,
        DataStreamAlignment = 6,
        TargetBackgroundGrid = 7,
        VideoWindow = 8,
        ConditionalAccess = 9,
        Iso639Language = 10,
        SystemClock = 11,
        MultiplexBufferUtilization = 12,
        Copyright = 13,
        MaximumBitrate = 14,
        PrivateData = 15,
        SmoothingBuffer = 16,
        Std = 17,
        IBP = 18,
        Mpeg4Video = 27,
        Mpeg4audio = 28,
        Iod = 29,
        Sl = 30,
        Fmc = 31,
        ExternalEsId = 32,
        MuxCode = 33,
        FmxBufferSize = 34,
        MultiplexBuffer = 35,
        ContentLabeling = 36,
        MetadataPointer = 37,
        Metadata = 38,
        MetadataStd = 39,
        AvcVideo = 40,
        Ipmp = 41,
        AvcTimingHrd = 42,
        Mpeg2AacAudio = 43,
        FlexMuxTiming = 44,
        // iso iec 13818-1 end

        // EN300468 (2011/10)
        NetworkName = 0x40,

        ServiceList = 0x41,
        Stuffing = 0x42,
        SatelliteDeliverySystem = 0x43,
        CableDeliverySystem = 0x44,
        VbiData = 0x45,
        VbiTeletext = 0x46,
        BouquetName = 0x47,
        ServiceDescriptor = 0x48,
        CountryAvailability = 0x49,
        Linkage = 0x4a,
        NvodReference = 0x4b,
        TimeShiftedService = 0x4c,
        ShortEvent = 0x4d,
        ExtendedEvent = 0x4e,
        TimeShiftedEvent = 0x4f,
        Component = 0x50,
        Mosaic = 0x51,
        StreamIdentifier = 0x52,
        ConditionalAccessIdentifier = 0x53,
        Content = 0x54,
        ParentalRating = 0x55,
        Teletext = 0x56,
        Telephone = 0x57,
        LocalTimeOffset = 0x58,
        Subtitling = 0x59,
        TerrestrialDeliverySystem = 0x5a,
        MultilingualNetworkName = 0x5b,
        MultilingualBouquetName = 0x5c,
        MultilingualServiceName = 0x5d,
        MultilingualComponent = 0x5e,
        PrivateDataSpecifier = 0x5f,
        ServiceMove = 0x60,
        ShortSmoothingBuffer = 0x61,
        FrequencyList = 0x62,
        PartialTransportStream = 0x63,
        DataBroadcast = 0x64,
        ScramblingDescriptor = 0x65,
        DataBroadcastId = 0x66,
        TransportStream = 0x67,
        Dsng = 0x68,
        Pdc = 0x69,
        Ac3 = 0x6a,
        AncillaryData = 0x6b,
        CellList = 0x6c,
        CellFrequencyLink = 0x6d,
        AnnouncementSupport = 0x6e,
        ApplicationSignalling = 0x6f,
        AdaptionFieldData = 0x70,
        ServiceIdentifier = 0x71,
        ServiceAvailability = 0x72,
        DefaultAuthority = 0x73,
        RelatedContent = 0x74,
        TvaId = 0x75,
        ContentIdentifier = 0x76,
        TimeSliceFecIdentifier = 0x77,
        EcmRepetitionRate = 0x78,
        S2SatelliteDeliverySystem = 0x79,
        EnhancedAc3 = 0x7a,
        Dts = 0x7b,
        Aac = 0x7c,
        XaitLocation = 0x7d,
        FtaContentManagement = 0x7e,
        Extension = 0x7f,
        // EN300468 (2011/10) end

        // Oscam Specific CA-Descriptors:
        EnigmaNamespace = 0x81,

        DemuxCaMaskDevice = 0x82,
        AdapterDevice = 0x83,
        PmtPid = 0x84,
        ServiceType = 0x85,
        DemuxDevice = 0x86,
        CaDevice = 0x87,
        // Oscam Specific End.

        Forbidden = 0xff
    }
}
